apiVersion: v1
kind: Deployment

metadata:
  name: airports-deployment
  label:
    app: airports

spec:
  replicas: 5
  selector:
    matchLabels:
      app: airports
  template:
    metadata:
      labels:
        app: airports
    spec:
      containers:
        - name: airports
          image: airports:5359823
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: url
          - name: API_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: airports-env
                key: url
          ports:
            - containerPort: 3333
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 512Mi