apiVersion: v1
kind: Service

metadata:
  name: airports-service
  labels:
    app: airports

spec:
  selector:
    app: airports
  type: ClusterIP
  ports:
  - name: airports-service
    port: 80
    targetPort: 3333
    protocol: TCP