apiVersion: v1
kind: Deployment

metadata:
  name: flightService-deployment
  label:
    app: flightService

spec:
  replicas: 5
  selector:
    matchLabels:
      app: flightService
  template:
    metadata:
      labels:
        app: flightService
    spec:
      containers:
        - name: flightService
          image: flightService:2368982
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: url
          - name: API_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: flightService-env
                key: url
          ports:
            - containerPort: 3333
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 512Mi