apiVersion: v1
kind: Service

metadata:
  name: flightService-service
  labels:
    app: flightService

spec:
  selector:
    app: flightService
  type: ClusterIP
  ports:
  - name: flightService-service
    port: 80
    targetPort: 3333
    protocol: TCP