apiVersion: v1
kind: Deployment

metadata:
  name: authentication-deployment
  label:
    app: authentication

spec:
  replicas: 5
  selector:
    matchLabels:
      app: authentication
  template:
    metadata:
      labels:
        app: authentication
    spec:
      containers:
        - name: authentication
          image: authentication:2359810
          env:
          - name: DATABASE_URL
            valueFrom:
              secretKeyRef:
                name: db-connection
                key: url
          - name: API_BASE_URL
            valueFrom:
              configMapKeyRef:
                name: authentication-env
                key: url
          ports:
            - containerPort: 3333
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 400m
              memory: 512Mi